[28/05/2018 20:20] ERROR red load_cogs 573: module 'discord' has no attribute 'Channel'
Traceback (most recent call last):
  File "red.py", line 570, in load_cogs
    owner_cog._load_cog(extension)
  File "C:\Users\m a r c e l\Documents\GitHub\Red-DiscordBot\cogs\owner.py", line 946, in _load_cog
    mod_obj = importlib.import_module(cogname)
  File "C:\Python35\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "C:\Users\m a r c e l\Documents\GitHub\Red-DiscordBot\cogs\audio.py", line 310, in <module>
    class Audio:
  File "C:\Users\m a r c e l\Documents\GitHub\Red-DiscordBot\cogs\audio.py", line 1190, in Audio
    async def audioset_notifychannel(self, ctx, channel: discord.Channel):
AttributeError: module 'discord' has no attribute 'Channel'
[28/05/2018 20:20] ERROR red load_cogs 573: You need the imgurpython module to use this.
pip3 install imgurpython
Traceback (most recent call last):
  File "red.py", line 570, in load_cogs
    owner_cog._load_cog(extension)
  File "C:\Users\m a r c e l\Documents\GitHub\Red-DiscordBot\cogs\owner.py", line 948, in _load_cog
    self.bot.load_extension(mod_obj.__name__)
  File "C:\Python35\lib\site-packages\discord\ext\commands\bot.py", line 704, in load_extension
    lib.setup(self)
  File "C:\Users\m a r c e l\Documents\GitHub\Red-DiscordBot\cogs\image.py", line 165, in setup
    raise RuntimeError("You need the imgurpython module to use this.\n"
RuntimeError: You need the imgurpython module to use this.
pip3 install imgurpython
[28/05/2018 20:20] ERROR red load_cogs 573: module 'discord' has no attribute 'Channel'
Traceback (most recent call last):
  File "red.py", line 570, in load_cogs
    owner_cog._load_cog(extension)
  File "C:\Users\m a r c e l\Documents\GitHub\Red-DiscordBot\cogs\owner.py", line 946, in _load_cog
    mod_obj = importlib.import_module(cogname)
  File "C:\Python35\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "C:\Users\m a r c e l\Documents\GitHub\Red-DiscordBot\cogs\mod.py", line 92, in <module>
    class Mod:
  File "C:\Users\m a r c e l\Documents\GitHub\Red-DiscordBot\cogs\mod.py", line 147, in Mod
    async def modlog(self, ctx, channel : discord.Channel=None):
AttributeError: module 'discord' has no attribute 'Channel'
[28/05/2018 20:33] ERROR owner load 74: [Errno 2] No such file or directory: 'lib\\botfile.json'
Traceback (most recent call last):
  File "C:\Users\m a r c e l\Documents\GitHub\Red-DiscordBot\cogs\owner.py", line 65, in load
    self._load_cog(module)
  File "C:\Users\m a r c e l\Documents\GitHub\Red-DiscordBot\cogs\owner.py", line 946, in _load_cog
    mod_obj = importlib.import_module(cogname)
  File "C:\Python35\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "C:\Users\m a r c e l\Documents\GitHub\Red-DiscordBot\cogs\OpenLeague.py", line 24, in <module>
    with open(os.path.join(sys.path[0], 'botfile.json')) as json_data:
FileNotFoundError: [Errno 2] No such file or directory: 'lib\\botfile.json'
